# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-OraLite
version:      0.11
version_from: lib/DBD/OraLite.pm
installdirs:  site
requires:
    DBD::SQLite:                   1
    DBI:                           1.3
    Digest::MD5:                   2
    File::Copy:                    2
    Math::Trig:                    1
    MIME::Base64:                  2
    Storable:                      2
    Test::More:                    0.44
    Text::Iconv:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
